name: Build ImmortalWrt APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step variabel tanggal (YYYYMMDD)
      - name: Get Current Date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build Package
        run: |
          sudo apt update && sudo apt install -y build-essential rsync wget tar zstd

          # Download & Ekstrak SDK ImmortalWrt
          wget https://downloads.immortalwrt.org/releases/25.12.0-rc2/targets/x86/64/immortalwrt-sdk-25.12.0-rc2-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf *.tar.zst --strip-components=1

          # Copy folder luci-app-imei-changer dari root workspace
          cp -r $GITHUB_WORKSPACE/luci-app-imei-changer package/

          # Verifikasi keberadaan Makefile
          if [ ! -f package/luci-app-imei-changer/Makefile ]; then
            echo "Error: Makefile tidak ditemukan di package/luci-app-imei-changer!"
            exit 1
          fi

          # Update Feeds & Compile
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          echo "CONFIG_PACKAGE_luci-app-imei-changer=y" >> .config
          make package/luci-app-imei-changer/compile V=s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: imei-changer-${{ steps.date.outputs.DATE }}
          path: bin/packages/**/*.apk
